id: OCIO-09
type: authoritative-document
title: 'Handbook for General Support Systems And  Major Applications Inventory Procedures'
owner: U.S. Department of Education
url: https://www.documentcloud.org/documents/2891702-Handbook-for-General-Support-Systems-and-Major.html
authoritative-url: http://www2.ed.gov/fund/contract/about/bsp.html
format: MSWord
