id: OCIO-11
type: authoritative-document
title: 'Handbook for Information Technology Security Configuration Management Planning Procedures'
owner: U.S. Department of Education
url: https://www.documentcloud.org/documents/2891703-Handbook-for-Information-Technology-Security.html
authoritative-url: http://www2.ed.gov/fund/contract/about/bsp.html
format: MSWord
