id:     task-2-1
type: task
source: RMF
number: 2.1
name:   Security Control Selection
description: >-
  Select the security controls for the information
  system and document the controls in the security plan.
