id:     task-2-3
type: task
source: RMF
number: 2.3
name:   Monitoring Strategy
description: >
  Develop a strategy for the continuous monitoring of
  security control effectiveness and any proposed/actual
  changes to the information system and its environment
  of operation.
