id: role-isse
source: RMF
name:
  full:             Information System Security Engineer
responsibilities:
  primary:
  secondary:
    - 1.1
    - 2.1
    - 2.2
    - 3.1
    - 3.2
    - 5.1
    - 6.3
description: >-
  The information system security engineer is an individual, group, or
  organization responsible for conducting information system security
  engineering activities.
