id: role-tl
type: role
title: Tech Lead
description: >-
  An engineer that leads the technical development of the project.
terms:
- text: Tech Lead
  same-as:
    term: TL
- text: TL
  same-as:
    term: Tech Lead